import { HarvesterModelSpec, ModuleBlueprint, TechNode } from '../types/colony';

export const GRID_SIZE = 80; // 80x80 tiles on the surface (expanded map)
export const TILE_SIZE = 48; // 48 pixels per tile
export const WORLD_WIDTH = GRID_SIZE * TILE_SIZE; // 3840 pixels
export const WORLD_HEIGHT = GRID_SIZE * TILE_SIZE; // 3840 pixels

export const MODULE_BLUEPRINTS: Record<string, ModuleBlueprint> = {
  command: {
    type: 'command',
    name: 'Command Outpost',
    category: 'command',
    description: 'Central operations hub. Coordinates communications, power relays, and life support.',
    costAlloy: 50,
    costCredits: 80,
    width: 3,
    height: 3,
    powerDelta: -8,
    o2Delta: 5,
    waterDelta: 5,
    foodDelta: 0,
    popCapacity: 4,
    color: '#0284c7', // Sky
    icon: 'Radio',
  },
  solar: {
    type: 'solar',
    name: 'Solar Array',
    category: 'power',
    description: 'Generates clean electric power from Martian sunlight. Output drops during dust storms and night.',
    costAlloy: 25,
    costCredits: 40,
    width: 2,
    height: 2,
    powerDelta: 40,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#eab308', // Yellow
    icon: 'Sun',
  },
  rtg: {
    type: 'rtg',
    name: 'RTG Nuclear Cell',
    category: 'power',
    description: 'Radioisotope thermoelectric generator providing reliable 24/7 baseload power regardless of storms.',
    costAlloy: 45,
    costCredits: 120,
    width: 2,
    height: 2,
    powerDelta: 25,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#f97316', // Orange
    icon: 'Zap',
  },
  battery: {
    type: 'battery',
    name: 'Battery Substation',
    category: 'power',
    description: 'Stores up to 400 kW of surplus power to keep life support online through the frigid Martian night.',
    costAlloy: 30,
    costCredits: 50,
    width: 2,
    height: 2,
    powerDelta: -2,
    batteryCapacity: 400,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#10b981', // Emerald
    icon: 'BatteryCharging',
  },
  scrubber: {
    type: 'scrubber',
    name: 'MOXIE O2 Scrubber',
    category: 'life_support',
    description: 'Extracts oxygen from Martian atmospheric CO2 via high-temperature solid oxide electrolysis.',
    costAlloy: 35,
    costCredits: 70,
    width: 2,
    height: 2,
    powerDelta: -10,
    o2Delta: 25,
    waterDelta: 0,
    foodDelta: 0,
    color: '#06b6d4', // Cyan
    icon: 'Wind',
  },
  vaporator: {
    type: 'vaporator',
    name: 'Moisture Vaporator',
    category: 'life_support',
    description: 'Condenses trace atmospheric humidity and subterranean permafrost into potable water.',
    costAlloy: 30,
    costCredits: 60,
    width: 2,
    height: 2,
    powerDelta: -8,
    o2Delta: 0,
    waterDelta: 20,
    foodDelta: 0,
    color: '#3b82f6', // Blue
    icon: 'Droplets',
  },
  greenhouse: {
    type: 'greenhouse',
    name: 'Hydroponic Bio-Dome',
    category: 'life_support',
    description: 'Aeroponic crops producing fresh nutrient rations and replenishing oxygen. Consumes water.',
    costAlloy: 45,
    costCredits: 90,
    width: 3,
    height: 3,
    powerDelta: -12,
    o2Delta: 12,
    waterDelta: -10,
    foodDelta: 18,
    color: '#22c55e', // Green
    icon: 'Sprout',
  },
  habitat: {
    type: 'habitat',
    name: 'Pressurized Habitat',
    category: 'life_support',
    description: 'Living quarters and crew amenities for up to 10 colonists. Supports colony workforce.',
    costAlloy: 55,
    costCredits: 110,
    width: 3,
    height: 3,
    powerDelta: -12,
    o2Delta: -10,
    waterDelta: -8,
    foodDelta: -8,
    popCapacity: 10,
    color: '#8b5cf6', // Violet
    icon: 'Home',
  },
  depot: {
    type: 'depot',
    name: 'Spice Melange Refinery',
    category: 'industry',
    description: 'Stores and purifies raw Martian spice into high-grade galactic canisters (+600 Spice storage).',
    costAlloy: 65,
    costCredits: 140,
    width: 3,
    height: 3,
    powerDelta: -16,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    spiceCapacity: 600,
    color: '#c026d3', // Fuchsia
    icon: 'Factory',
  },
  garage: {
    type: 'garage',
    name: 'Harvester Garage & Bay',
    category: 'industry',
    description: 'Primary deployment hangar and offloading dock for autonomous spice harvesters.',
    costAlloy: 60,
    costCredits: 130,
    width: 3,
    height: 3,
    powerDelta: -14,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#e11d48', // Rose
    icon: 'Truck',
  },
  research: {
    type: 'research',
    name: 'Ares Science Lab',
    category: 'research',
    description: 'Generates Tech Points to unlock rover enhancements, terraforming tech, and energy matrices.',
    costAlloy: 50,
    costCredits: 150,
    width: 3,
    height: 3,
    powerDelta: -15,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    techRate: 1.8,
    color: '#6366f1', // Indigo
    icon: 'Atom',
  },
  launchpad: {
    type: 'launchpad',
    name: 'Orbital Trade Launchpad',
    category: 'industry',
    description: 'Cargo rocket pad. Load spice onto Earth-bound shuttles for massive galactic credit payouts!',
    costAlloy: 110,
    costCredits: 280,
    width: 4,
    height: 4,
    powerDelta: -20,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#d97706', // Amber
    icon: 'Rocket',
  },
  radar: {
    type: 'radar',
    name: 'Seismic & Storm Radar',
    category: 'command',
    description: 'Monitors subterranean tremors and scans the horizon for incoming dust storms.',
    costAlloy: 35,
    costCredits: 80,
    width: 2,
    height: 2,
    powerDelta: -8,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#14b8a6', // Teal
    icon: 'Scan',
  },
  medbay: {
    type: 'medbay',
    name: 'Trauma & Medical Bay',
    category: 'life_support',
    description: 'Advanced cryogenic bio-stasis pods and radioprotective gene clinics. Boosts colonist health recovery (+1.2%/s), cleanses cellular radiation damage, and reduces long-term physical degradation.',
    costAlloy: 45,
    costCredits: 95,
    width: 2,
    height: 2,
    powerDelta: -10,
    o2Delta: -2,
    waterDelta: -3,
    foodDelta: 0,
    color: '#10b981', // Emerald / Cyan medical
    icon: 'HeartPulse',
  },
  miner: {
    type: 'miner',
    name: 'Ore Extraction Miner',
    category: 'industry',
    description: 'Automated drill rig extracting raw iron ore from subterranean deposits.',
    costAlloy: 40,
    costCredits: 90,
    width: 2,
    height: 2,
    powerDelta: -12,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#78350f', // Amber-900 (ore)
    icon: 'Pickaxe',
  },
  refinery: {
    type: 'refinery',
    name: 'Ore Smelter Refinery',
    category: 'industry',
    description: 'Processes raw ore into high-grade structural alloy for construction.',
    costAlloy: 50,
    costCredits: 100,
    width: 3,
    height: 3,
    powerDelta: -15,
    o2Delta: 0,
    waterDelta: 0,
    foodDelta: 0,
    color: '#94a3b8', // Slate-400 (alloy)
    icon: 'Factory',
  },
};

export const HARVESTER_SPECS: Record<string, HarvesterModelSpec> = {
  scout: {
    model: 'scout',
    name: 'Scout Harvester Mk-I',
    description: 'Lightweight, rapid four-wheeler. Nimble exploration and quick small-load harvesting.',
    costAlloy: 35,
    costCredits: 70,
    maxCargo: 60,
    speed: 2.6,
    harvestRate: 18,
    maxHealth: 100,
  },
  heavy: {
    model: 'heavy',
    name: 'Heavy Sandcrawler Mk-II',
    description: 'Six-wheel industrial powerhouse equipped with dual vacuum scoops and 180kg spice tank.',
    costAlloy: 75,
    costCredits: 160,
    maxCargo: 180,
    speed: 1.8,
    harvestRate: 30,
    maxHealth: 220,
  },
  titan: {
    model: 'titan',
    name: 'Titan Dread-Harvester Mk-III',
    description: 'Massive all-terrain tracked behemoth. High-capacity spice drill, storm shields, 400kg vault.',
    costAlloy: 140,
    costCredits: 350,
    maxCargo: 400,
    speed: 1.3,
    harvestRate: 52,
    maxHealth: 450,
  },
  ore_rover: {
    model: 'ore_rover',
    name: 'Excavator Ore Rover',
    description: 'Heavy duty crawler designed to drill, collect, and transport raw iron ore back to the Ore Refinery.',
    costAlloy: 45,
    costCredits: 80,
    maxCargo: 150,
    speed: 2.0,
    harvestRate: 25,
    maxHealth: 180,
  },
};

export const TECH_TREE: TechNode[] = [
  {
    id: 'solar_tracking',
    name: 'Sun-Tracking Gimbal',
    category: 'power',
    description: 'Motorized mounts align solar arrays dynamically with the Martian sun (+35% solar yield).',
    cost: 40,
    unlocked: false,
    requires: [],
    effectLabel: '+35% Solar Power',
  },
  {
    id: 'rover_turbo',
    name: 'Turbocharged Magnetic Treads',
    category: 'spice',
    description: 'Enhanced brushless motors improve all harvester roaming speeds (+35% speed).',
    cost: 50,
    unlocked: false,
    requires: [],
    effectLabel: '+35% Harvester Speed',
  },
  {
    id: 'spice_centrifuge',
    name: 'High-Density Melange Refinement',
    category: 'spice',
    description: 'Centrifugal separators purify spice crystals, increasing trade credit value by +40%.',
    cost: 75,
    unlocked: false,
    requires: ['rover_turbo'],
    effectLabel: '+40% Spice Sale Value',
  },
  {
    id: 'titan_holds',
    name: 'Nanotube Cargo Compactor',
    category: 'spice',
    description: 'Pressurizes raw spice dust, boosting all harvesters cargo capacity by +50%.',
    cost: 100,
    unlocked: false,
    requires: ['spice_centrifuge'],
    effectLabel: '+50% Harvester Cargo Capacity',
  },
  {
    id: 'hydro_recycler',
    name: 'Closed-Loop Moisture Reclamation',
    category: 'life_support',
    description: 'Recovers 50% of water used in hydroponic green domes.',
    cost: 60,
    unlocked: false,
    requires: [],
    effectLabel: '-50% Hydroponic Water Consumption',
  },
  {
    id: 'deep_well_drilling',
    name: 'Sub-Permafrost Thermal Wells',
    category: 'life_support',
    description: 'Taps deep geothermal subterranean ice layers for +50% moisture vaporator output.',
    cost: 90,
    unlocked: false,
    requires: ['hydro_recycler'],
    effectLabel: '+50% Water Vaporator Extraction',
  },
  {
    id: 'nuclear_enrichment',
    name: 'Advanced RTG Pellets',
    category: 'power',
    description: 'Refined plutonium isotopes boost RTG power generation by +50%.',
    cost: 80,
    unlocked: false,
    requires: ['solar_tracking'],
    effectLabel: '+50% RTG Power Output',
  },
  {
    id: 'storm_hardening',
    name: 'Electrostatic Dust Deflectors',
    category: 'engineering',
    description: 'Shields modules and rovers, halving dust storm penalties and damage.',
    cost: 110,
    unlocked: false,
    requires: ['nuclear_enrichment'],
    effectLabel: '-50% Dust Storm Damage & Slow',
  },
  {
    id: 'terraforming_genesis',
    name: 'Atmospheric Genesis Genesis Engine',
    category: 'engineering',
    description: 'The pinnacle of Mars colonization: massive atmospheric scrubbers begin warming the red planet!',
    cost: 200,
    unlocked: false,
    requires: ['titan_holds', 'storm_hardening', 'deep_well_drilling'],
    effectLabel: 'Colony Terraforming Achieved!',
  },
];
